name: Run script and upload file

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Mintimate'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Prepare Selenium
        # https://github.com/marketplace/actions/setup-chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: chrome_data.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update"
          add: 'source target'